# -*- coding: utf-8 -*-
"""yawn_lstm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Ck389Cc5UXpxpG9ZLMld9jTVmIcuSLv
"""

# Commented out IPython magic to ensure Python compatibility.
#IMPORTS
import numpy as np
import pandas as pd
import cv2
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
from keras.layers import Dropout
# %tensorflow_version 2.x
from tensorflow import keras
import tensorflow as tf
import time
from sklearn.model_selection import train_test_split

#import dataset 
df=pd.read_excel('lstm_yawn2.xlsx')

df.shape

#extract values 
values = df.values
values=values.astype('float32')
#extract features and target value 
X=values[:,:-1]
Y=values[:,10:]
print(X.shape)
print(Y.shape)

#train test split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.15, random_state=4)



#reshape for LSTM model
x_train = x_train.reshape((x_train.shape[0], 1, x_train.shape[1]))
x_test= x_test.reshape((x_test.shape[0], 1, x_test.shape[1]))
print(x_train.shape, y_train.shape,  x_test.shape, y_test.shape)

#create model 
model = Sequential()
model.add(LSTM(2, input_shape=(x_train.shape[1],x_train.shape[2])))
model.add(Dense(2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# implement early stopping and train model 
es = keras.callbacks.EarlyStopping(monitor='accuracy', mode='max', verbose=1,patience=25,restore_best_weights=True)
model.fit(x_train, y_train, epochs=4000,batch_size=32,callbacks=[es])

model.evaluate(x_test, y_test)

model.save('model_yawn4')

!zip -r /content/model_yawn4.zip /content/model_yawn4

